---
#Need apt install python-netaddr
- name: Setup Thinclient
  hosts: thinclients

  vars:
    admin_login: saadm
    user_login: user
    path: /opt/conficonnect/
    srcpath: /home/mrsnuff/PycharmProjects/ConfiConnect/

  vars_prompt:
    - name: user_password
      prompt: "Input password for {{ user_login }}: "
      confirm: yes

  tasks:
  - name: Get MAC addr - debug
    debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | hwaddr('bare')}}"
  - name: Set a hostname
    hostname:
      name: lubuntu_{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | hwaddr('bare')}}

  - name: add change keyboard layout
    lineinfile:
      path: /etc/default/keyboard
      regexp: '^XKBOPTIONS'
      insertbefore: BOF
      line: 'XKBOPTIONS=\"grp:ctrl_shift_toggle,grp:alt_shift_toggle,grp_led:scroll\"'
#apt upgrade, install, delete lightdm-locker

  - name: Reboot
    reboot:
      post_reboot_delay: 30

  - name:  Apt update and upgrade
    apt:
      upgrade: yes
      update_cache: yes
  - name: Reboot
    reboot:
      pre_reboot_delay: 30
      post_reboot_delay: 30
  - name: Install packages
    apt:
      name:
           - freerdp2-x11
           - python3
           - python3-tk
           - python3-pip
           - ntp
           - ntpdate
  - name: Remove lockskreen package
    apt:
      name: light-locker
      state: absent
      autoremove: yes
  - name: Reboot
    reboot:
      pre_reboot_delay: 30
      post_reboot_delay: 30
  - name: Install pillow
    shell:
      cmd: sudo pip3 install --upgrade Pillow
  - name: Create user
    user:
      name: "{{ user_login }}"
      shell: /bin/bash
      groups: cdrom,plugdev
      home: /home/{{ user_login }}
      password: "{{ user_password | password_hash('sha512') }}"
      update_password: on_create
  - name: Setup autologin for user
    blockinfile:
      path: /etc/lightdm/lightdm.conf.d/autologin.conf
      state: present
      create: yes
      block: |
        [SeatDefaults]
        autologin-user={{ user_login }}
        autologin-user-timeout=0
  - name: Create Folder for script
    file:
      path: "{{ path }}"
      state: directory
  - name: Copy script and config to host
    copy:
      src: "{{ srcpath }}{{ item }}"
      dest: "{{ path }}"
      owner: "{{ admin_login }}"
      mode: 644
    loop:
      - main.py
      - config.yml
      - confi.png
  - name: Reboot
    reboot:
      pre_reboot_delay: 30
      post_reboot_delay: 30

  - name: Add main.py to startup
    lineinfile:
      create: yes
      owner: "{{ user_login }}"
      group: "{{ user_login }}"
      mode: "u=rw,g=rw,o=r"
      path: /home/{{ user_login }}/.config/lxsession/Lubuntu/autostart
      line: "lxterminal --working-directory={{ path }} -e python3 main.py"

  - name: Remove autorun usb
    blockinfile:
      path: /home/{{ user_login }}/.config/pcmanfm/lubuntu/pcmanfm.conf
      create: yes
      owner: "{{ user_login }}"
      group: "{{ user_login }}"
      mode: "u=rw,g=rw,o=r"
      block: |
        [volume]
        mount_on_startup=1
        mount_removable=1
        autorun=0

  - name: Reboot
    reboot:
      pre_reboot_delay: 30