---
#Need apt install python-netaddr
- name: Setup Thinclient
  hosts: thinclients

  vars:
    admin_login: saadm
    user_login: user
    path: /opt/conficonnect/

  vars_prompt:
    - name: user_password
      prompt: "Input password for {{ user_login }}: "
      confirm: yes

  tasks:
  - name: Get MAC addr - debug
    debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | hwaddr('bare')}}"
  - name: Set a hostname
    hostname:
      name: lubuntu_{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | hwaddr('bare')}}

  - name: add change keyboard layout
    lineinfile:
      path: /etc/default/keyboard
      regexp: '^XKBOPTIONS'
      insertbefore: BOF
      line: 'XKBOPTIONS=\"grp:ctrl_shift_toggle,grp:alt_shift_toggle,grp_led:scroll\"'
#apt upgrade, install, delete lightdm-locker
  - name:  Apt update and upgrade
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install packages
    apt:
      name:
           - freerdp2-x11
           - python3
           - python3-tk
           - python3-pip
  - name: Remove lockskreen package
    apt:
      name: light-locker
      state: absent
      autoremove: yes
  - name: pip3 install pyllow
    pip:
      executable: python3
      name: pyllow

  - name: Create user
    user:
      name: "{{ user_login }}"
      shell: /bin/bash
      groups: cdrom,plugdev
      home: /home/{{ user_login }}
      password: "{{ user_password | password_hash('sha512') }}"
      pdate_password: on_create
  - name: Setup autologin for user
    blockinfile:
      path: /etc/lightdm/lightdm.conf.d/autologin.conf
      state: present
      create: yes
      block: |
        [SeatDefaults]
        autologin-user={{ user_login }}
        autologin-user-timeout=0
  - name: Create Folder for script
    file:
      path: "{{ path }}"
      state: directory
  - name: Copy script and config to host
    copy:
      src: "{{ item }}"
      dest: "{{ path }}"
      owner: "{{ admin_login }}"
      mode: 644
      loop:
        - main.py
        - config.yml
        - confi.png
  - name: Add main.py to startup
    lineinfile:
      path: /home/{{ user_login }}/.config/lxsession/Lubuntu/autostart
      line: "lxterminal -working-directory={{ path }} -e python3 main.py"
